language: node_js
node_js:
  - "lts/*"
deploy:
  provider: npm
  skip_cleanup: true
  email: avens19@gmail.com
  api_key:
    secure: hYg5hVV2HyF/8uVoZU7H6ngRYa6iW/sfT/Ht/ZUVcCImsyKyndv1Y7x4g5h0L8xZhYS3ul7ciPx35gM70mnwaNLiy6rzGVIkaBuqtQCfltbSadr5CpwXj/zQ4B+AVoLCcJzJt2gdwpJGaU1cztIbqwSyz1IUU1jnzFplEDfYZbGQVbPr2Wspewc1q88kKZamcBU7pkFZjfKgSFVahRyG8uROQUf4+rP5HVr1LMmkPZ7MgWDlw4Rzi51soD8ucIZ0GCF/6RZgEllPoQx942SyS/DEDibAWSdyWN5ojrIU3c46X+xjSY+0JSE9JoRdezvD2RRK3vEBF1XoanT2wPDhAgXGkg4io3zcIUmTAKqlyWr+3ciXFrbDCse/A4Mhcmlfn67TPFBpStSK990yqhWTIboGDBCRV3eVa58oS8HgJ6UtGZ2mZNQsRjZnhKuSQzqHgoQcjG2EphEpkl7SvZdpQWoGyRG0bF3oQRmdzDKmbPsaXgwlG00gVyRYbL/fnYD++SjxeySIv/R8WqwCpjrOOO6b4lXmPUa6g+rz70q/AlYMEiTgDz86XZeyqvCJFDwmuyvVgy8T9eST6XJvjJ7Gl9QkqD4pEghgixceiWj5oQpAoENgDfHmWchcE9fDGiYTSAYiNU7xLl0uyId/wKQk+fDTbIq3viY3Mhwn5kbOBts=
  on:
    tags: true
    repo: avens19/winston-sumologic-transport
