language: node_js
node_js:
- lts/*
script:
- npm test
- npm run tslint
- npm run eslint
before_deploy:
- sed -i -e s/0.0.0/$TRAVIS_TAG/ package.json
deploy:
  provider: npm
  skip_cleanup: true
  email: avens19@gmail.com
  api_key:
    secure: h00PhqIZPr9ZrLw/Ip9o/ns1rRj0LsjirKJpAl9lzmUDpNPKoxPnpAG6oFMY0Kz2VnsOx10SLS9ELaB0jrTDD2zoThPPNjvzOEiCgOGDXOZY8scg9hSWaCIUXux2LImnWc2pE7cFnKoWB77gFnXLHOua09xBZJhv/N1aYqFhoceA0XOTbkGyfO39fCA34Mzk0CuF67NNF/oWOD9P6g5G32moMsZt4dMCsXKPrA+RdNIgB9PFse7/Qan2EGwDaCN4FDRlOt9u6Ug8LcAgx11VYjuEud8SNuF9phc/mtJCjGkmyJDoqY+xSBrGfoGKzJoPGkw2AA+R7f85WBFlyTnGYxDscjnPpdSFdihrSA9v2TbSwnFbQ4KhkJ+Oplw0Qke0kUwHXK4d8IUwUWDix7lcoaMkjybP0Vup4yjQqJZ9YmfwJzKqq0SYKK05VZONfdrMtitphWnYZ9stPOB5EKumuy8fmCgYp1z2wdqcMPAlBeDJapJN41Sh9RkNiikqj/aFhMuv68dJZw32UrYq6DNzp3Uu3Xl2KNFcrhIennzn9oUj/CZwiS7m5sasI7+qCKp6onoEg6MmqixPpicG4t2JgXwl/pYfZGCYZGUX64XWNwsTBXWcACGJR3hpZCXnRfg1qGjU5eWfgmStvjzXVltKzyNjPnJWPj3NXR9yytoYn2A=
  on:
    tags: true
    repo: avens19/winston-sumologic-transport
